version: '2.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    networks:
      - es
    environment:
      - "ES_JAVA_OPTS=-Xms26g -Xmx26g"
      - "bootstrap.memory_lock=true"
      - "cluster.name=capsid-prototype"
      - "node.name=capsid6"
      - "node.master=true"
      - "node.data=true"
      - "network.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "transport.publish_host=capsid6.res.oicr.on.ca"
      - "discovery.zen.ping.unicast.hosts=capsid1.res.oicr.on.ca,capsid2.res.oicr.on.ca,capsid4.res.oicr.on.ca,capsid6.res.oicr.on.ca,capsid8.res.oicr.on.ca"
      - "discovery.zen.minimum_master_nodes=3"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    healthcheck:
      test: "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1"
      interval: 1m30s
      timeout: 50s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    networks:
      - es
    depends_on:
      - elasticsearch
    environment:
      LOGGING_QUIET: "true"

networks:
  es:

volumes:
  esdata:
    driver: local
